<form action="http://thepointless.com/search?wide=1" id="cse-search-box">
<div>
<input type="hidden" name="c" value="search" />
<input type="hidden" name="wide" value="1" />
<input type="hidden" name="cx" value="partner-pub-6115341109827821:wtsvef-tqds" />
<input type="hidden" name="cof" value="FORID:10" />
<input type="hidden" name="ie" value="ISO-8859-1" />
<input type="text" name="q" size="24" />
<input type="submit" name="sa" value="Search" />
</div>
</form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&amp;lang=en"></script>
