<?php
	$meta_title = "contact us";
?>
<p>It wouldn't surprise me if you found something on this site to be egregiously awesome. But, I'm not actually thrilled about being handed things.</p>
<p>I mean, I'm not saying I'm like Iron Man, but ... </p>
<p style='text-align: center;'>
	<img src='/images/dont-hand-me-things.gif' />
</p>
<p>... well, I am pretty much just like Iron Man. And to be honest, that makes me pretty hard to get ahold of.</p>
<p>But, if it's urgent, you can send a message to <b><code>tonystark</code></b> <i>at</i> <b>this domain</b>, and ...</p>
<p>Well.</p>
<p>I'm not actually sure if that mailbox exists. But, if it does, it's obviously mine. And, I <i>think</i> I know how to check my email.</p>
<p>Probably. Or at least maybe. So, I'll get back to you.</p>
<p><del>Probably.</del> <i>Maybe.</i></p>