<?php

	$meta_title = "about us";

?>

<div class='content'>
	<div class='padded navbar float-right' style='width: 90px;'>
		<img alt='factory' title='our dot-com. image stolen from http://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Factory_icon.svg/75px-Factory_icon.svg.png' src='/images/75px_Factory.png' style='width: 75px; display: inline;'/>
	</div>
	<div class='content'>
		<b>thepointless.com is a serious dot-com.</b>
		We work in rooms inside buildings and type on keyboards &mdash; many of which are even attached to computers. Our building looks like a two-dimnensional, monocolor factory from very far away.
	</div>
</div>

<div class='content'>
	<div class='padded navbar' style='width: 90px;'>
		<img alt='gears' title='the gears of productivity. image stolen from http://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Cog-scripted-svg-green.svg/49px-Cog-scripted-svg-green.svg.png' src="/images/49px_GreenCog.png" style='width: 75px; display: inline;'/>
	</div>
	<div class='content'>
		<b>We work hard and with gears.</b>
		Lots and lots of gears. And that's hard stuff to beat. Gears. Yes, gears are what make it happen. If you ain't got gears, you ain't got gears.
	</div>
</div>

<div class='content'>
	<div class='padded navbar float-right' style='width: 90px;'>
		<img alt='people' title='professionals. image stolen from http://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Icon_of_three_people_in_different_shades_of_grey.svg/75px-Icon_of_three_people_in_different_shades_of_grey.svg.png' src="images/75px_ThreeGrayPeople.png" style='width: 75px; display: inline;' />
	</div>
	<div class='content'>
		<b>Lean, Synergetic, Agile Efficiency.</b>
		That's what our awesome people do with the gears. And then they do <b>Analytics</b> and <b>ROI</b> and stuff. And then more working with gears. And boy, do we ever.
	</div>
</div>

<div>
	<b>You're welcome.</b>
</div>

<tpdc:share></tpdc:share>

