<?php
$meta_title = "that awkward moment";
?>
<h3>... When you used to have a page here and now you don't.</h3>
<p>This is really just temporarily disabled. If <a href='/apps/shooty-ship-presidential/index.html'>things go well</a>, I'm sure we'll have this back and ready for you <i>no time.</i></p>
<p>If things <i>don't</i> go well, "temporary" could be longer than expected.</p>
<p>So, please contribute by honoring our great president. Please shoot his face with our shooty ship!</p>
<p><a href='/apps/shooty-ship-presidential/index.html'>Pew pew pew!</a></p>
<tpdc:share></tpdc:share>