<?php

	$meta_title = "find stuff";

?>

<style type='text/css'>

.field {
	background-image: url('');
	width: 100%;
	height: 400px;
}

.lookable {
	cursor:url(/images/magnify.cur), -moz-zoom-in;
}

</style>

Poke around. Look for things. The further you get from <a href='/find-stuff'>home</a>, the more difficult it gets, and the rarer the stuff you can find.

<table class='field'>
	<tr>
		<td class='lookable'>something</td>
	</tr>
</table>
