<?php

	$meta_title = "thepointless.com";
	$require_theme = 'default';

?>
<p>Welcome, dear friend.</p>
<p>It's spooky out there. We're already seeing <b>lots of spooky masks</b> out there. If you're scared, we don't blame you, and we're here to help.</p>
<p><b>Shooty Ship</b> has taken flight against <i>spooooky pumkins</i>. Take the control and join the <b>fight against fear!</b></p>
<p style='text-align: center; font-size: x-large; font-weight: bold;'>
	<a href='/apps/shooty-ship-pumpkin-smash/index.html' target='_blank'>
		<img width='256' height='256' src='/apps/shooty-ship-pumpkin-smash/img/icon.png' />
		<br />Click to Play!
	</a>
</p>
<p>Support <b>us</b> in supporting <b>you</b> fight spooky things this year and <b>Play Shooty Ship Pumpkin Smash</b>.</p>
<p style='text-align: center;'><b>Play</b> it and <b>Share</b> your score!</p>
<p>Don't forget to <b>install</b> the app after your first round of play for <b>so you're never stuck without it</b>.</p>
<tpdc:share
	text="I support thepointless.com in this vErY SpoOkY HalLoWeeN."
></tpdc:share>
