<?php
	$meta_title = "Shooty Ship Pumpkin Smash";
?>
<p>Shooty Ship is under a Halloween Horror Assault!</p>
<table>
	<tr>
		<td>
			<img src="/images/shooty-ship-pumpkin-smash-icon.png" style='width: 200px; height: 200px;'/>
		</td>
	</tr>
		<td>
			<a href="https://play.google.com/store/apps/details?id=com.thepointless.shootyshippumpkinsmash">See it in the Play Store!</a>
		</td>
	</tr>
</table>
<p>Show your support by getting your copy of Shooty Ship Pumpkin Smash from the Google Play store!</p>
