<?php
	$meta_title = "sign in";
?>
<h3>Just kidding.</h3>
<p>Yup. We used to have authenticated content. And we will again.</p>
<p>In the meantime, this is a duck.</p>
<p style='text-align: center;'>
	<img
		width="256"
		alt="Bactrian Camel (PSF)"
		src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Bactrian_Camel_%28PSF%29.png/256px-Bactrian_Camel_%28PSF%29.png"
	/>
</p>
<p>Trust me. I know ducks.</p>
<tpdc:share
	image="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Bactrian_Camel_%28PSF%29.png/256px-Bactrian_Camel_%28PSF%29.png"
	text="I found this really awesome picture of a duck. Trust me. I definitely know ducks."
></tpdc:share>