<?php

	$meta_title = "thepointless.com";
	$require_theme = 'default';

?>
<p>Welcome, dear friend.</p>
<p>We're in the middle of tidying things up around here. As such, some of the stuff you might normally expect to see here is temporarily out of order.</p>
<p><b><i>Good news though</i></b>, we still have plenty of things for you to do in the meantime. One such thing you can do, which would <i>really</i> delight us, would be to honor our great president by <b>shooting him in the face with our <code>Shooty Ship</code></b>.</p>
<p style='text-align: center; font-size: x-large; font-weight: bold;'>
	<a href='/apps/shooty-ship-presidential/index.html' target='_blank'>
		<img width='256' height='256' src='/apps/shooty-ship-presidential/img/icon.png' />
		<br />Click to Play!
	</a>
</p>
<p>Support <u>us</u> by having fun <i>honoring</i> our fearless leader.</p>
<p style='text-align: center;'><b>Play</b> it and <b>Share</b> your score!</p>
<p>And, if you're having as much fun honoring our REALLY PROBABLY VERY BIG LEADER as we are, <b>install</b> it (from within the app) so you're never stuck without it!</p>
<tpdc:share
	text="I support thepointless.com in this year of 2020 or whatever it is."
></tpdc:share>
