<?php

	$meta_title = "TERMS OF USE";

?>
<style type='text/css'>
	h5 {
		margin-top: 2em;
		margin-bottom: 0.5em;
		text-decoration: underline;
	}

	#tos div {
		font-size: smaller;
	}
</style>

<div id='tos'>

	<div>Welcome to our highly esteemed dot-com. By accessing thepointless.com you agree to adhere to the following terms. They’re just your typical terms of use. And so as usual, read them carefully or all your base are belong to us.</div>

	<h5>PRIVACY</h5>
	<div>We may or may not make every attempt possible to glean your most personal information and distribute it to the masses. If you find your birthday, social security number, or little black book in the public domain and suspect thepointless.com is to blame, we told you so.</div>

	<h5>COPYRIGHT</h5>
	<div>All the stuff on this site belongs to us. If you publish or share any of our content via Facebook, Apebook, Twitter, Sniffer, Dipper, or any other idiotic social or non-social medium of any kind, an associate will visit you and educate you in the matters of pain and suffering. Also, any personal information you intentionally or unintentionally share, including but not limited to your name, belongs to us: you may no longer use it.</div>

	<h5>TRADEMARKS</h5>
	<div>thepointless.com’s trademarks, favorite songs and poetry, favorite color, and anything else we feel embodies the spirit and mission our our website may not be used in connection with anything else in the world, ever.</div>

	<h5>LICENSE AND SITE ACCESS</h5>
	<div>You are not licensed to use any content on this site at all in any way. You may not download, look at, or think about anything from our site. By reading these terms, you are in violation of the terms, and if we ever find out who you are, you have no chance to escape. Make your time.</div>

	<h5>YOUR MEMBERSHIP ACCOUNT</h5>
	<div>We are free to cancel your account whenever we want to and for whatever reason we want to. If you complain about it, we will call you a cry-baby and/or other silly, but equally hurtful names.</div>

	<h5>REVIEWS, COMMENTS, EMAILS, AND OTHER CONTENT</h5>
	<div>You are free to send us communications. And you may contribute to areas of the site which are open for contribution. In doing so, you grant us the right to publish, republish, profit from, edit, delete, ignore, laugh at, and otherwise do whatever we want with your contributions and communications. We owe you nothing in terms of monetary compensation, recognition, or tissue to wipe the tears of defeat and humiliation from your stupid face.</div>

	<h5>RISK OF LOSS</h5>
	<div>If you give us money with the expectation of receiving something in return, you may never receive the expected items, and it is never our fault.</div>

	<h5>INJURY FROM USE</h5>
	<div>It is perfectly likely that you will be injured during or because of your use of this site or its products. We are not responsible for any of your injuries, ever. And we retain the right to laugh at you for doing stupid things that result in injury.</div>

	<h5>PRODUCT DESCRIPTIONS</h5>
	<div>We’ve done everything we intend to do to ensure that all of the stuff and not stuff we sell and don’t sell is described as accurately as humanly possible. If something you receive from us, like a 1 or a 0, doesn’t appear as described, appearing as a 2 or 3 for instance, it is completely and entirely somebody else’s fault. We are not to blame.</div>

	<h5>WARRANTY</h5>
	<div>We do not provide any warranty on any thing or service, intellectual or otherwise. We claim the right to include defects and self-destruct mechanism in all of our products, services, etc.</div>

	<h5>APPLICABLE LAW</h5>
	<div>By visiting thepointless.com, you agree that the laws and whims of thepointless.com, as maintained in the mind of its sole proprietor, will govern these terms of service and any disputes you may have with us and our products, services, policies, people, philosophies, or associates.</div>

	<h5>SITE POLICIES, MODIFICATION, AND SEVERABILITY</h5>
	<div>Your visit to thepointless.com is governed not only by this terms of service agree, but by all other text and words that appear on this site. We reserve the right to change our terms whenever we want. And if some crazy legal authority decides that any portion of these terms or conditions is invalid for any reason, the invalid portion shall be deemed severable, and the remaining terms and conditions are still totally valid.</div>

	<h5>ONE LAST THING</h5>
	<div>As stated indicated above, republishing any portion of these terms of service is in direction violation of them, and we reserve the right to beat the everliving daylights out of you for doing so.</div>

</div>

<tpdc:share></tpdc:share>

