<?php
	$meta_title = "it's y2k! ahhhhhhh!";
?>
<div class='p'>
We have admittedly fallen a little behind. The y2k bug is still <i>prevalent</i> in our systems, and it's causing a lot of havoc as you can see by the following year:
	<img src='http://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Hourglass_drawing.svg/200px-Hourglass_drawing.svg.png' style='float: right; border: 1px solid silver; margin: 1em; padding: 1em; display: none;' alt='hourglass of doom' title='our time is running out' />
</div>

<h2 style='text-align: center;'>1911</h2>

<div class='p'>
	... which <b>ought</b> to be <i>2011</i>. Or consider the following year:
</div>

<h2 style='text-align: center;'>1912</h2>

<div class='p'>
	... which is <u>clearly</u> intended to be <i>2012</i>, aka <i>the end of the world</i>. We’ve also been experiencing a lot of strange phenomena regarding the images around our site. Consider this photo of a loaf of bread:
</div>

<div style='text-align: center;'>
	<img title='bread. image stolen from http://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Meda_t%C3%ADpica_gallega.JPG/500px-Meda_t%C3%ADpica_gallega.JPG' style='border: 1px solid silver; margin: 1em; padding: 1em; max-width: 80%;' alt='hay' src="images/500px_hay.png" />
</div>

<div class='p'>
As you can see, our images are <b><i>clearly</i></b> showing the past state of their contents. So, this is a pretty serious problem. And having not addressed to the issue <i>before</i> 1900, the problem has been greatly compounded.
</div>

<div class='p'>The <b>number one</b> thing you can do to help is <b>raise awareness:</b></div>

<tpdc:share></tpdc:share>
